# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oktaws < Formula
  desc "Helps getting aws cli credentials using okta"
  homepage "https://github.com/gerdou/oktaws"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gerdou/oktaws/releases/download/v1.1.1/oktaws_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "ba2223e6050921e99abfeacd758ed391cb1dd62352cb6028a9ac2cc3064d7b8f"

      define_method(:install) do
        bin.install "oktaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gerdou/oktaws/releases/download/v1.1.1/oktaws_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b58441e5e4d75ace6e8f12677f220d18eac104e104d31083b5ea0a9917bb47c"

      define_method(:install) do
        bin.install "oktaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerdou/oktaws/releases/download/v1.1.1/oktaws_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6c13f1955abc892f9ecd0d3fb05738748adf88282df51cef9c1b49a10f26ffb0"
      define_method(:install) do
        bin.install "oktaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gerdou/oktaws/releases/download/v1.1.1/oktaws_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "23625be30889737ca116fc6d572dba8aec3450fb91133a4dd78a656c00d7531c"
      define_method(:install) do
        bin.install "oktaws"
      end
    end
  end

  test do
    system "#{bin}/oktaws --version"
  end
end
