# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oktaws < Formula
  desc "Helps getting aws cli credentials using okta"
  homepage "https://github.com/vahid-haghighat/oktaws"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vahid-haghighat/oktaws/releases/download/v1.0.0/oktaws_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d9c2921945944374c709827adb14cfa3417068e11b3701654f67b5a849abfa8f"

      def install
        bin.install "oktaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vahid-haghighat/oktaws/releases/download/v1.0.0/oktaws_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7549a832ee0db2dfe39573050cd6deaf4bab4b62a0f1308c753413980be069d2"

      def install
        bin.install "oktaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/oktaws/releases/download/v1.0.0/oktaws_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1563f5e08f3ae4a1f0ece54f88a0ab87c6ed7720c0dc873f410e14f2d9f5f9b8"
      def install
        bin.install "oktaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/oktaws/releases/download/v1.0.0/oktaws_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "35b6871660560e7921e26ef5b0809f3659ae990b0ea34881c0aedd48edf53689"
      def install
        bin.install "oktaws"
      end
    end
  end

  test do
    system "#{bin}/oktaws --version"
  end
end
